_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
gpus: 1
precision: 16

min_epochs: 1
max_epochs: 10

#progress_bar_refresh_rate: 10
resume_from_checkpoint: null
